#!/usr/bin/env python3
"""Assemble a self-contained ARM64 guest program into bytes Voland can run.

    guest_asm.py inc  program.s  out.inc   # C array for tests (#include-able)
    guest_asm.py nro  program.s  out.nro   # a homebrew NRO (DESIGN.md §12)

The program must be position-independent and live in .text alone (ADR /
literal / branch addressing only): the tool takes the assembled .text
bytes and refuses any object that still carries relocations, because
there is no linker in the loop. Requires clang with the AArch64 target
(any Apple or LLVM clang). Generated files are committed, so building and
testing Voland never needs this tool or an ARM toolchain.

NRO layout written here (switchbrew "NRO"): the image starts with NroStart
(a branch to the code, the MOD0 offset, padding) and the 0x70-byte
NroHeader; .text is the whole file, followed by an empty .rodata/.data,
and `bss` bytes of zero-initialised memory after it.
"""
import os
import struct
import subprocess
import sys
import tempfile

ELF_SECTION_HEADER = struct.Struct("<IIQQQQIIQQ")
SHT_RELA = 4
SHT_REL = 9
NRO_HEADER_OFFSET = 0x10
NRO_HEADER_SIZE = 0x70
NRO_START_SIZE = 0x10
PAGE = 0x1000
NRO_BSS_DEFAULT = 0x10000


def assemble(source: str) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        obj = os.path.join(tmp, "out.o")
        subprocess.run(["clang", "-c", "-target", "aarch64-none-elf", source, "-o", obj], check=True)
        data = open(obj, "rb").read()
    if data[:4] != b"\x7fELF" or data[4] != 2 or data[5] != 1:
        sys.exit("not a little-endian ELF64 object")
    shoff = struct.unpack_from("<Q", data, 0x28)[0]
    shentsize, shnum, shstrndx = struct.unpack_from("<HHH", data, 0x3A)
    sections = [ELF_SECTION_HEADER.unpack_from(data, shoff + i * shentsize) for i in range(shnum)]
    strtab = sections[shstrndx]
    names = data[strtab[4]: strtab[4] + strtab[5]]

    def name_of(sec):
        end = names.index(b"\0", sec[0])
        return names[sec[0]:end].decode()

    text = None
    for sec in sections:
        name, sh_type, size = name_of(sec), sec[1], sec[5]
        if sh_type in (SHT_RELA, SHT_REL) and size:
            sys.exit(f"{source}: relocations in {name}; guest programs must be position-independent in .text")
        if name == ".text":
            text = data[sec[4]: sec[4] + size]
        elif name in (".data", ".rodata", ".bss") and size:
            sys.exit(f"{source}: put everything in .text ({name} is not supported)")
    if text is None:
        sys.exit(f"{source}: no .text")
    return text


def write_inc(code: bytes, source: str, out: str) -> None:
    name = os.path.splitext(os.path.basename(source))[0]
    lines = [f"/* Generated by tools/guest_asm.py from {os.path.basename(source)} - do not edit. */",
             f"static const unsigned char k_guest_{name}[] = {{"]
    for i in range(0, len(code), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in code[i:i + 12]) + ",")
    lines.append("};")
    open(out, "w").write("\n".join(lines) + "\n")


def write_nro(code: bytes, out: str) -> None:
    if len(code) < NRO_START_SIZE + NRO_HEADER_SIZE or code[NRO_HEADER_OFFSET:NRO_HEADER_OFFSET + 4] != b"\0\0\0\0":
        sys.exit("NRO programs must start with `b start` and reserve 0x7C bytes (see tests/guest/hello.s)")
    text = bytearray(code)
    text_size = (len(text) + PAGE - 1) // PAGE * PAGE
    text += b"\0" * (text_size - len(text))
    header = struct.pack(
        "<4sIII" "IIIIII" "II" "32s" "II" "IIIIII",
        b"NRO0", 0, text_size, 0,
        0, text_size,          # .text: file offset, size
        text_size, 0,          # .rodata
        text_size, 0,          # .data
        NRO_BSS_DEFAULT, 0,
        b"VOLAND-GUEST".ljust(32, b"\0"),
        0, 0,
        0, 0, 0, 0, 0, 0,
    )
    assert len(header) == NRO_HEADER_SIZE
    text[NRO_HEADER_OFFSET:NRO_HEADER_OFFSET + NRO_HEADER_SIZE] = header
    open(out, "wb").write(bytes(text))


def main() -> None:
    if len(sys.argv) != 4 or sys.argv[1] not in ("inc", "nro"):
        sys.exit(__doc__)
    mode, source, out = sys.argv[1:]
    code = assemble(source)
    if mode == "inc":
        write_inc(code, source, out)
    else:
        write_nro(code, out)
    print(f"{out}: {len(code)} bytes of code")


if __name__ == "__main__":
    main()
